# Generated by Django 5.0.6 on 2024-06-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_cities_country_alter_cities_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='weather',
        ),
        migrations.AddField(
            model_name='subscription',
            name='cities',
            field=models.ManyToManyField(related_name='cities', to='weather.cities'),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='description',
            field=models.CharField(default='common', max_length=50),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='icon',
            field=models.CharField(default='01d', max_length=20),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='temperature',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='cities',
            name='country',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
