# Generated by Django 5.0.6 on 2024-06-06 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0008_weatherdata_created_at_weatherdata_updated_at'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cities',
            table='City',
        ),
        migrations.AlterModelTable(
            name='weatherdata',
            table='Weather',
        ),
    ]
