# Generated by Django 5.0.6 on 2024-06-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0009_alter_cities_table_alter_weatherdata_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='timezone',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
