# Generated by Django 5.0.6 on 2024-06-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0011_alter_weatherdata_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='subscription',
        ),
        migrations.AddField(
            model_name='myuser',
            name='subscription',
            field=models.ManyToManyField(related_name='users', to='weather.subscription'),
        ),
    ]
