# Generated by Django 5.0.6 on 2024-06-15 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0012_remove_myuser_subscription_myuser_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='notification_period',
            field=models.IntegerField(choices=[(1, '1 hour'), (3, '3 hours'), (6, '6 hours'), (12, '12 hours')]),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='city',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='weather.cities'),
        ),
    ]
