# Generated by Django 5.0.6 on 2024-06-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0013_alter_subscription_notification_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
